---
title: "Analysis of data requirements"
author: "Annelinde Lettink"
date: "02/02/2024"
output: 
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
rm(list = ls())
gc()
knitr::opts_chunk$set(echo = TRUE)
## User settings
# Directory path and name of castor export file
filepath.castor <- "/Users/annelindelettink/Documents/Work MacBook Pro Annelinde/My Little Moves (MLM)/Castor export"
filename.castor <- "/20231007/Study/My_Little_Moves_export_20231007.csv"
# Directory path and name of app data (frequency and duration per day)
filepath.app <- "/Users/annelindelettink/Documents/Work MacBook Pro Annelinde/My Little Moves (MLM)/App-data/20230918"
filename.app <- "/20230918_MLMapp_activiteit_gedrag_duur_per_dag.csv"
# Directory path for epochdata hip and wrist
epochdir.hip <- "/Users/annelindelettink/Documents/Work MacBook Pro Annelinde/My Little Moves (MLM)/Accelerometer data/Measurement1/rerun/epochdata/hip/nonwear_removed"
epochdir.wrist <- "/Users/annelindelettink/Documents/Work MacBook Pro Annelinde/My Little Moves (MLM)/Accelerometer data/Measurement1/rerun/epochdata/wrist/nonwear_removed"

savedir <- "/Users/annelindelettink/Documents/Work MacBook Pro Annelinde/My Little Moves (MLM)/Comparison MLM-app and accelerometer data/Analyses/output/reliability/"

# source functions directly from file, to be replaced by package installation:
my_functions_folder =   "/Users/annelindelettink/Documents/Work MacBook Pro Annelinde/My Little Moves (MLM)/Comparison MLM-app and accelerometer data/Analyses/AxivityMLMapp/R"
for (function_file in dir(my_functions_folder, full.names = T)) source(function_file) #load functions

# Load in Castor data (this file includes participant characteristics)
data.castor <- load.castor(filepath.castor, filename.castor, cohort = c(3))
```

```{r libraries, include = FALSE}
library(dplyr)
library(psych)
library(CTT)
library(compositions)
```

### Determine criteria for generation of reliable estimates

In this script, [description here]

## My Little Moves app 

```{r Load MLM app data, echo=FALSE}
# Load app data for all cohorts
data.app <- load.app(filepath.app, filename.app, cohort = c(1,2,3), measurementperiod = 1, sep = ";")
# Note 98MLM027 (wrong in Castor, code was used by 98MLM028 adjusted at 2023-10-10 but not yet in export, this subj. was excluded so use the following lines L63-64 for exclusion of data)
# 04MLM004 born <31 weeks
index <- which(data.app$castorID %in% c("04MLM004", "98MLM027"))
data.app <- data.app[-index,] # Remove rows

# Number of participants at start
paste0("number of participants: ", length(unique(data.app$castorID)))

# Select files that provide => 8 hours on => 2 day
valid_data_12h2d <- validday.app(data.app, minhours = 12, mindays = 2, CoDa = TRUE, savedir = filepath.app) 
paste0("participants provide => 12 h on => 2 day: ", length(unique(valid_data_12h2d$castorID)), "(", length(unique(valid_data_12h2d$castorID))/length(unique(data.app$castorID))*100, " %)")
```

```{r Week weekend variability MLM app, echo=FALSE}
# Examine differences between week and weekend days

outcomes <- c("PA", "SB", "sleep", "ilr1", "ilr2")
hours <- c(12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24)

week_weekend_differences <- data.frame()
counter = 1

for(h in 1: length(hours)){
  # Load in data
  data <- validday.app(data.app, minhours = hours[h], mindays = 2, savedir = filepath.app, CoDa = TRUE) 
  # Random sample data of participants to at least one weekend and one week day
  WKWKND <- data.frame()
  for(pp in 1:length(unique(data$castorID))){
    tmp <- data[data$castorID == unique(data$castorID)[pp],]
    if(length(unique(tmp$weekenddag)) == 2){
      WKWKND <- rbind(WKWKND, tmp)
    }
  }
  for(out in 1:length(outcomes)){
    week_weekend_differences[counter, 1] <- hours[h]
    week_weekend_differences[counter, 2] <- outcomes[out]
    col <- which(colnames(WKWKND) == outcomes[out])

    if(outcomes[out] %in% c("PA", "SB", "sleep")){
      week_weekend_differences[counter, 3] <- median(unlist(subset(WKWKND, weekenddag == 0)[col]), na.rm = T)
      week_weekend_differences[counter, 4] <- quantile(unlist(subset(WKWKND, weekenddag == 0)[col]), probs = 0.25, na.rm = T)
      week_weekend_differences[counter, 5] <- quantile(unlist(subset(WKWKND, weekenddag == 0)[col]), probs = 0.75, na.rm = T)
      week_weekend_differences[counter, 6] <- median(unlist(subset(WKWKND, weekenddag == 1)[col]), na.rm = T)
      week_weekend_differences[counter, 7] <- quantile(unlist(subset(WKWKND, weekenddag == 1)[col]), probs = 0.25, na.rm = T)
      week_weekend_differences[counter, 8] <- quantile(unlist(subset(WKWKND, weekenddag == 1)[col]), probs = 0.75, na.rm = T)
      week_weekend_differences[counter, c(9:12)] <- NA
      if(outcomes[out] == "PA"){
          differences <- lme4::lmer(log(PA + 0.001) ~ weekenddag + (1 | castorID), WKWKND, REML = F) } 
      else if(outcomes[out] == "SB"){
          differences <- lme4::lmer(log(SB + 0.001) ~ weekenddag + (1 | castorID), WKWKND, REML = F) } 
      else{
          differences <- lme4::lmer(log(sleep + 0.001) ~ weekenddag + (1 | castorID), WKWKND, REML = F)
       }
    
    } else {
      week_weekend_differences[counter, c(3:8)] <- NA
      week_weekend_differences[counter, 9] <- mean(unlist(subset(data, weekenddag == 0)[col]), na.rm = T)
      week_weekend_differences[counter, 10] <- sd(unlist(subset(data, weekenddag == 0)[col]), na.rm = T)
      week_weekend_differences[counter, 11] <- mean(unlist(subset(data, weekenddag == 1)[col]), na.rm = T)
      week_weekend_differences[counter, 12] <- sd(unlist(subset(data, weekenddag == 1)[col]), na.rm = T)
      if(outcomes[out] == "ilr1"){
        differences <- lme4::lmer(ilr1 ~ weekenddag + (1 | castorID), WKWKND, REML = F) }
      else{
        differences <- lme4::lmer(ilr2 ~ weekenddag + (1 | castorID), WKWKND, REML = F) }
    }
    test <- car::Anova(differences)
    week_weekend_differences[counter, 13] <- test$`Pr(>Chisq)`
    counter = counter + 1
  }
  colnames(week_weekend_differences) <- c("hours", "outcome", "Median_week", "Q1_week", "Q3_week", "Median_weekend", "Q1_weekend", "Q3_weekend", "Mean_week", "sd_week", "Mean_weekend", "sd_weekend", "p_value")
}

save(week_weekend_differences, file = paste0(savedir, "MLMapp/week_weekend.RData")) # Save week weekend difference tests
write.csv(week_weekend_differences, file = paste0(savedir, "MLMapp/week_weekend.csv"))

```

```{r Single day ICCs MLM app all criteria, include = FALSE}
days <- c(2, 3, 4, 5, 6, 7)
hours <- c(12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24)
n.pp <- data.frame()
temp.icc <- data.frame(ncol(3))
day <- c()
hour <- c()
outcome <- c()
repetition <- c()
count = 0
result_data <- data.frame()

# For all valid wear criteria
for(d in 1:length(days)){
  for(h in 1: length(hours)){
    # if(file.exists(paste0(filepath.app, "/valid_data_", hours[h], "h", days[d], "d.RData"))){
    #   load(paste0(filepath.app, "/valid_data_", hours[h], "h", days[d], "d.RData"))
    #   data <- valid_data
    #   rm(valid_data)
    # } else {
      data <- validday.app(data.app, minhours = hours[h], mindays = days[d], savedir = filepath.app, CoDa = TRUE) 
    # }
    
    cat(paste0("participants provide at least ", hours[h], " hours on ", days[d], " days: ", ... = length(unique(data$castorID)), "(", length(unique(data$castorID))/length(unique(data.app$castorID))*100, " %)", "/n"))
    n.pp[d, h] <- length(unique(data$castorID))
    temp <- cbind(data$castorID, data$weekenddag, data$dag, data[,22:26])
    colnames(temp) <- c("id", "weekendday", "day", "PA", "SB", "sleep", "ilr1", "ilr2")
    temp$id <- as.factor(temp$id)
    temp$weekendday <- as.factor(temp$weekendday)
    temp$day <- as.factor(temp$day)

    #Select random number of days, repeat this five times and save the average single day ICC.
    ndays <- rep(1:days[d], length(unique(temp$id)))
    ntimes = 5 #42 number permutations from 2 out 7
    for(variable in 4:ncol(temp)){ #Calculate the mean ICC for each outcome
      outcome <- c(outcome, colnames(temp)[variable])
      count = count + 1
      temp.icc_temp <- data.frame()
      for(rep in 1:ntimes){
        repetition <- c(repetition, rep)
        
        if(week_weekend_differences$p_value[which(week_weekend_differences$hours == hours[h] & week_weekend_differences$outcome == colnames(temp)[variable])] < .05){ # If there are differences between week and weekend days
            sample <- temp %>% group_by(id, weekendday) %>% slice_sample(n = days[d]-1) # Include at least one weekend day
        } else{
            sample <- temp %>% group_by(id) %>% slice_sample(n = days[d])
        }

        var.icc <- data.frame()
        #sample[which(is.na(sample[,variable])), variable] <- 0
        temp.var <- cbind(sample$id,  rep(1:days[d], nrow(sample)), sample[,variable])
        colnames(temp.var) <- c("id", "day", "outcome")
          
        # Create matrix as input for days (cols) and participants (rows) containing the variable values
        m <- reshape(temp.var, idvar = "id", timevar = "day", direction = "wide")

        if(variable == 3 | variable == 4 | variable == 5){
          n <- log(m[,2:ncol(m)] + 0.001)
          m <- cbind(m[,1], n)
        }
        
        # Calculate ICC
        icc <- psych::ICC(m[,-1])$results[2,]
        temp.icc_temp <- rbind(temp.icc_temp, c(icc$ICC, icc$`lower bound`, icc$`upper bound`))
      }
      temp.icc <- rbind(temp.icc, colMeans(temp.icc_temp))
      day <- c(day, days[d])
      hour <- c(hour, hours[h])

      cat("Outcome: ", paste0(colnames(sample)[variable], ": ICC ", hours[h], " hours ", days[d], " days: ", colMeans(temp.icc_temp)))
    }
  }
}

temp.icc <- cbind(hour, day, outcome, temp.icc)
colnames(temp.icc) <- c("hour", "day", "outcome", "ICC", "LB", "UB")

write.table(n.pp, file = paste0(savedir, "MLMapp/reliability_sample_size.txt"), sep = ",", quote = FALSE, row.names = F)
write.csv(temp.icc, file = paste0(savedir, "MLMapp/ICC_SpearmanBrown.csv"))

save(temp.icc, file = paste0(savedir, "MLMapp/ICC_SpearmanBrown.RData")) # Save data that meets the valid day criterion

```

```{r Average ICCs MLM app wear time hours Spearman-Brown, echo=FALSE}
hours <- c(12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24)
temp.icc.PA <- temp.icc[which(temp.icc$outcome == "PA"),]
temp.icc.SB <- temp.icc[which(temp.icc$outcome == "SB"),]
temp.icc.sleep <- temp.icc[which(temp.icc$outcome == "sleep"),]
temp.icc.ilr1 <- temp.icc[which(temp.icc$outcome == "ilr1"),]
temp.icc.ilr2 <- temp.icc[which(temp.icc$outcome == "ilr2"),]

ICC.PA <- data.frame()
ICC.SB <- data.frame()
ICC.sleep <- data.frame()
ICC.ilr1 <- data.frame()
ICC.ilr2 <- data.frame()
sb.PA <- c()
sb.SB <- c()
sb.sleep <- c()
sb.ilr1 <- c()
sb.ilr2 <- c()

# Averages for all day criteria
for(h in 1:length(hours)){

  ICC.PA <- rbind(ICC.PA, colMeans(temp.icc.PA[which(temp.icc.PA$hour == hours[h]),4:6]))
  sb.PA <- c(sb.PA, CTT::spearman.brown(ICC.PA[h,1], .7, "r")[[1]])
  ICC.SB <- rbind(ICC.SB, colMeans(temp.icc.SB[which(temp.icc.SB$hour == hours[h]),4:6]))
    sb.SB <- c(sb.SB, CTT::spearman.brown(ICC.SB[h,1], .7, "r")[[1]])
  ICC.sleep <- rbind(ICC.sleep, colMeans(temp.icc.sleep[which(temp.icc.sleep$hour == hours[h]),4:6]))
    sb.sleep <- c(sb.sleep, CTT::spearman.brown(ICC.sleep[h,1], .7, "r")[[1]])
  ICC.ilr1 <- rbind(ICC.ilr1, colMeans(temp.icc.ilr1[which(temp.icc.ilr1$hour == hours[h]),4:6]))
    sb.ilr1 <- c(sb.ilr1, CTT::spearman.brown(ICC.ilr1[h,1], .7, "r")[[1]])
  ICC.ilr2 <- rbind(ICC.ilr2, colMeans(temp.icc.ilr2[which(temp.icc.ilr2$hour == hours[h]),4:6]))
sb.ilr2 <- c(sb.ilr2, CTT::spearman.brown(ICC.ilr2[h,1], .7, "r")[[1]])
}

rownames(ICC.PA) <- hours
ICC.PA <- cbind(ICC.PA, sb.PA)
colnames(ICC.PA) <- c("ICC", "LB", "UB", "SB70")
write.csv(ICC.PA, file = paste0(savedir, "MLMapp/ICC_Spearman_PA.csv"))

ICC.SB <- cbind(ICC.SB, sb.SB)
colnames(ICC.SB) <- c("ICC", "LB", "UB", "SB70")
rownames(ICC.SB) <- hours
write.csv(ICC.SB, file = paste0(savedir, "MLMapp/ICC_Spearman_SB.csv"))

rownames(ICC.sleep) <- hours
ICC.sleep <- cbind(ICC.sleep, sb.sleep)
colnames(ICC.sleep) <- c("ICC", "LB", "UB", "SB70")
write.csv(ICC.sleep, file = paste0(savedir, "MLMapp/ICC_Spearman_sleep.csv"))

rownames(ICC.ilr1) <- hours
ICC.ilr1 <- cbind(ICC.ilr1, sb.ilr1)
colnames(ICC.ilr1) <- c("ICC", "LB", "UB", "SB70")
write.csv(ICC.ilr1, file = paste0(savedir, "MLMapp/ICC_Spearman_ilr1.csv"))

rownames(ICC.ilr2) <- hours
ICC.ilr2 <- cbind(ICC.ilr2, sb.ilr2)
colnames(ICC.ilr2) <- c("ICC", "LB", "UB", "SB70")
write.csv(ICC.ilr2, file = paste0(savedir, "MLMapp/ICC_Spearman_ilr2.csv"))
```

## Accelerometers

```{r Load Axivity data, echo=FALSE}
# Number of accelerometer files at start
filelist.hip <- list.files(epochdir.hip, pattern = ".RData")
filelist.wrist <- list.files(epochdir.wrist, pattern = ".RData")
paste0("accelerometer files hip: ", length(filelist.hip))
paste0("accelerometer files wrist: ", length(filelist.wrist))

# Select files that provide => 12 hours on at least two days
savedir.hip <- paste0(epochdir.hip, "/2d12h")
validday.axivity(epochdir.hip, epochlength = 5, minhours = 12, mindays = 2, savedir = savedir.hip, data.castor)
savedir.wrist <- paste0(epochdir.wrist, "/2d12h")
validday.axivity(epochdir.wrist, epochlength = 5, minhours = 12, mindays = 2, savedir = savedir.wrist, data.castor)
paste0("hip: accelerometer files that provide at least 12 h on 2 days: ", length(list.files(savedir.hip, pattern = ".RData")), "(", length(list.files(savedir.hip, pattern = ".RData"))/length(filelist.hip)*100, " %)")
paste0("wrist: accelerometer files that provide at least 12 h on 2 days: ", length(list.files(savedir.wrist, pattern = ".RData")), "(", length(list.files(savedir.wrist, pattern = ".RData"))/length(filelist.wrist)*100, " %)")
```


```{r Week weekend variability MLM app, echo=FALSE}
# Examine differences between week and weekend days

outcomes <- c("PA", "SB", "sleep", "ilr1", "ilr2")
hours <- c(12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24)

week_weekend_differences <- data.frame()
counter = 1

for(h in 1: length(hours)){
  # Load in data
  data <- validday.app(data.app, minhours = hours[h], mindays = 2, savedir = filepath.app, CoDa = TRUE) 
  # Random sample data of participants to at least one weekend and one week day
  WKWKND <- data.frame()
  for(pp in 1:length(unique(data$castorID))){
    tmp <- data[data$castorID == unique(data$castorID)[pp],]
    if(length(unique(tmp$weekenddag)) == 2){
      WKWKND <- rbind(WKWKND, tmp)
    }
  }
  for(out in 1:length(outcomes)){
    week_weekend_differences[counter, 1] <- hours[h]
    week_weekend_differences[counter, 2] <- outcomes[out]
    col <- which(colnames(WKWKND) == outcomes[out])

    if(outcomes[out] %in% c("PA", "SB", "sleep")){
      week_weekend_differences[counter, 3] <- median(unlist(subset(WKWKND, weekenddag == 0)[col]), na.rm = T)
      week_weekend_differences[counter, 4] <- quantile(unlist(subset(WKWKND, weekenddag == 0)[col]), probs = 0.25, na.rm = T)
      week_weekend_differences[counter, 5] <- quantile(unlist(subset(WKWKND, weekenddag == 0)[col]), probs = 0.75, na.rm = T)
      week_weekend_differences[counter, 6] <- median(unlist(subset(WKWKND, weekenddag == 1)[col]), na.rm = T)
      week_weekend_differences[counter, 7] <- quantile(unlist(subset(WKWKND, weekenddag == 1)[col]), probs = 0.25, na.rm = T)
      week_weekend_differences[counter, 8] <- quantile(unlist(subset(WKWKND, weekenddag == 1)[col]), probs = 0.75, na.rm = T)
      week_weekend_differences[counter, c(9:12)] <- NA
      if(outcomes[out] == "PA"){
          differences <- lme4::lmer(log(PA + 0.001) ~ weekenddag + (1 | castorID), WKWKND, REML = F) } 
      else if(outcomes[out] == "SB"){
          differences <- lme4::lmer(log(SB + 0.001) ~ weekenddag + (1 | castorID), WKWKND, REML = F) } 
      else{
          differences <- lme4::lmer(log(sleep + 0.001) ~ weekenddag + (1 | castorID), WKWKND, REML = F)
       }
    
    } else {
      week_weekend_differences[counter, c(3:8)] <- NA
      week_weekend_differences[counter, 9] <- mean(unlist(subset(data, weekenddag == 0)[col]), na.rm = T)
      week_weekend_differences[counter, 10] <- sd(unlist(subset(data, weekenddag == 0)[col]), na.rm = T)
      week_weekend_differences[counter, 11] <- mean(unlist(subset(data, weekenddag == 1)[col]), na.rm = T)
      week_weekend_differences[counter, 12] <- sd(unlist(subset(data, weekenddag == 1)[col]), na.rm = T)
      if(outcomes[out] == "ilr1"){
        differences <- lme4::lmer(ilr1 ~ weekenddag + (1 | castorID), WKWKND, REML = F) }
      else{
        differences <- lme4::lmer(ilr2 ~ weekenddag + (1 | castorID), WKWKND, REML = F) }
    }
    test <- car::Anova(differences)
    week_weekend_differences[counter, 13] <- test$`Pr(>Chisq)`
    counter = counter + 1
  }
  colnames(week_weekend_differences) <- c("hours", "outcome", "Median_week", "Q1_week", "Q3_week", "Median_weekend", "Q1_weekend", "Q3_weekend", "Mean_week", "sd_week", "Mean_weekend", "sd_weekend", "p_value")
}

save(week_weekend_differences, file = paste0(savedir, "MLMapp/week_weekend.RData")) # Save week weekend difference tests
write.csv(week_weekend_differences, file = paste0(savedir, "MLMapp/week_weekend.csv"))

```


```{r Single day ICCs MLM app all criteria, include = FALSE}
days <- c(2, 3, 4, 5, 6, 7)
hours <- c(8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24)
n.pp <- data.frame()
temp.icc <- data.frame(ncol(3))
day <- c()
hour <- c()
outcome <- c()
repetition <- c()
count = 0
result_data <- data.frame()

# For all valid wear criteria
for(d in 1:length(days)){
  for(h in 1: length(hours)){
    if(file.exists(paste0(filepath.app, "/valid_data_", hours[h], "h", days[d], "d.RData"))){
      load(paste0(filepath.app, "/valid_data_", hours[h], "h", days[d], "d.RData"))
      data <- valid_data
      rm(valid_data)
    } else {
      data <- validday.app(data.app, minhours = hours[h], mindays = days[d], savedir = filepath.app) 
    }
    
    cat(paste0("participants provide at least ", hours[h], " hours on ", days[d], " days: ", ... = length(unique(data$castorID)), "(", length(unique(data$castorID))/length(unique(data.app$castorID))*100, " %)", "/n"))
    n.pp[d, h] <- length(unique(data$castorID))
    temp <- cbind(data$castorID, data$dag, data[,22:26])
    colnames(temp) <- c("id", "day", "PA", "SB", "sleep", "ilr1", "ilr2")
    temp$id <- as.factor(temp$id)
    temp$day <- as.factor(temp$day)

    #Select random number of days, repeat this five times and save the average single day ICC.
    ntimes = 5 #42 number permutations from 2 out 7
    for(variable in 3:ncol(temp)){ #Calculate the mean ICC for each outcome
      outcome <- c(outcome, colnames(temp)[variable])
      count = count + 1
      temp.icc_temp <- data.frame()
      for(rep in 1:ntimes){
        repetition <- c(repetition, rep)
        sample <- temp %>% group_by(id) %>% slice_sample(n = days[d])
        var.icc <- data.frame()
        sample[which(is.na(sample[,variable])), variable] <- 0
        
        temp.var <- cbind(sample$id,  ndays, sample[,variable])
        colnames(temp.var) <- c("id", "day", "outcome")
          
        # Create matrix as input for days (cols) and participants (rows) containing the variable values
        m <- reshape(temp.var, idvar = "id", timevar = "day", direction = "wide")

        if(variable == 3 | variable == 4 | variable == 5){
          n <- log(m[,2:ncol(m)] + 0.001)
          m <- cbind(m[,1], n)
        }
        
        # Calculate ICC
        icc <- psych::ICC(m[,-1])$results[2,]
        temp.icc_temp <- rbind(temp.icc_temp, c(icc$ICC, icc$`lower bound`, icc$`upper bound`))
      }
      temp.icc <- rbind(temp.icc, colMeans(temp.icc_temp))
      day <- c(day, days[d])
      hour <- c(hour, hours[h])

      cat("Outcome: ", paste0(colnames(sample)[variable], ": ICC ", hours[h], " hours ", days[d], " days: ", colMeans(temp.icc_temp)))
    }
  }
}

temp.icc <- cbind(hour, day, outcome, temp.icc)
colnames(temp.icc) <- c("hour", "day", "outcome", "ICC", "LB", "UB")

write.table(n.pp, file = paste0(savedir, "MLMapp/reliability_sample_size.txt"), sep = ",", quote = FALSE, row.names = F)
save(temp.icc, file = paste0(savedir, "MLMapp/ICC_SpearmanBrown.RData")) # Save data that meets the valid day criterion
```

```{r Average ICCs MLM app wear time hours Spearman-Brown, echo=FALSE}
hours <- c(8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24)
temp.icc.PA <- temp.icc[which(temp.icc$outcome == "PA"),]
temp.icc.SB <- temp.icc[which(temp.icc$outcome == "SB"),]
temp.icc.sleep <- temp.icc[which(temp.icc$outcome == "sleep"),]
temp.icc.ilr1 <- temp.icc[which(temp.icc$outcome == "ilr1"),]
temp.icc.ilr2 <- temp.icc[which(temp.icc$outcome == "ilr2"),]

ICC.PA <- data.frame()
ICC.SB <- data.frame()
ICC.sleep <- data.frame()
ICC.ilr1 <- data.frame()
ICC.ilr2 <- data.frame()
sb.PA <- c()
sb.SB <- c()
sb.sleep <- c()
sb.ilr1 <- c()
sb.ilr2 <- c()

# Averages for all day criteria
for(h in 1:length(hours)){

  ICC.PA <- rbind(ICC.PA, colMeans(temp.icc.PA[which(temp.icc.PA$hour == hours[h]),4:6]))
  sb.PA <- c(sb.PA, CTT::spearman.brown(ICC.PA[h,1], .7, "r")[[1]])
  ICC.SB <- rbind(ICC.SB, colMeans(temp.icc.SB[which(temp.icc.SB$hour == hours[h]),4:6]))
    sb.SB <- c(sb.SB, CTT::spearman.brown(ICC.SB[h,1], .7, "r")[[1]])
  ICC.sleep <- rbind(ICC.sleep, colMeans(temp.icc.sleep[which(temp.icc.sleep$hour == hours[h]),4:6]))
    sb.sleep <- c(sb.sleep, CTT::spearman.brown(ICC.sleep[h,1], .7, "r")[[1]])
  ICC.ilr1 <- rbind(ICC.ilr1, colMeans(temp.icc.ilr1[which(temp.icc.ilr1$hour == hours[h]),4:6]))
    sb.ilr1 <- c(sb.ilr1, CTT::spearman.brown(ICC.ilr1[h,1], .7, "r")[[1]])
  ICC.ilr2 <- rbind(ICC.ilr2, colMeans(temp.icc.ilr2[which(temp.icc.ilr2$hour == hours[h]),4:6]))
sb.ilr2 <- c(sb.ilr2, CTT::spearman.brown(ICC.ilr2[h,1], .7, "r")[[1]])
}

rownames(ICC.PA) <- hours
ICC.PA <- cbind(ICC.PA, sb.PA)
colnames(ICC.PA) <- c("ICC", "LB", "UB", "SB70")
rownames(ICC.SB) <- hours
ICC.SB <- cbind(ICC.SB, sb.SB)
colnames(ICC.SB) <- c("ICC", "LB", "UB", "SB70")
rownames(ICC.sleep) <- hours
ICC.sleep <- cbind(ICC.sleep, sb.sleep)
colnames(ICC.sleep) <- c("ICC", "LB", "UB", "SB70")
rownames(ICC.ilr1) <- hours
ICC.ilr1 <- cbind(ICC.ilr1, sb.ilr1)
colnames(ICC.ilr1) <- c("ICC", "LB", "UB", "SB70")
rownames(ICC.ilr2) <- hours
ICC.ilr2 <- cbind(ICC.ilr2, sb.ilr2)
colnames(ICC.ilr2) <- c("ICC", "LB", "UB", "SB70")
```


```{r Spearman-brown accelerometers}
sb7 <- c()
sb8 <- c()
sb9 <- c()

for(row in 1:nrow(temp.icc)){
  sb7 <- c(sb7, CTT::spearman.brown(temp.icc$ICC[row], .7, "r")[[1]])
  sb8 <- c(sb8, CTT::spearman.brown(temp.icc$ICC[row], .8, "r")[[1]])
  sb9 <- c(sb9, CTT::spearman.brown(temp.icc$ICC[row], .9, "r")[[1]])
}

temp.icc <- cbind(temp.icc, sb7)
temp.icc <- cbind(temp.icc, sb8)
temp.icc <- cbind(temp.icc, sb9)

# Function to calculate reliability using Bison et al. (2019) formula with hours per day
calculate_reliability_level <- function(single_day_icc, num_days) {
      reliability <- (num_days * single_day_icc) / (1 + (num_days - 1) * single_day_icc)
  return(reliability)
}

rel <- c()
for (rows in 1:nrow(temp.icc)) {
  rel <- c(rel, calculate_reliability_level(temp.icc[rows,]$ICC, temp.icc[rows,]$day))
}
temp.icc <- cbind(temp.icc, rel)

PA <- temp.icc[which(temp.icc$outcome == "PA"),]
SB <- temp.icc[which(temp.icc$outcome == "SB"),]
sleep <- temp.icc[which(temp.icc$outcome == "sleep"),]
ilr1 <- temp.icc[which(temp.icc$outcome == "ilr1"),]
ilr2 <- temp.icc[which(temp.icc$outcome == "ilr2"),]

write.table(PA, file = paste0(savedir, "MLMapp/reliability_table_PA.txt"), sep = ",", quote = FALSE, row.names = F)
write.table(SB, file = paste0(savedir, "MLMapp/reliability_table_SB.txt"), sep = ",", quote = FALSE, row.names = F)
write.table(sleep, file = paste0(savedir, "MLMapp/reliability_table_sleep.txt"), sep = ",", quote = FALSE, row.names = F)
write.table(ilr1, file = paste0(savedir, "MLMapp/reliability_table_ilr1.txt"), sep = ",", quote = FALSE, row.names = F)
write.table(ilr2, file = paste0(savedir, "MLMapp/reliability_table_ilr2.txt"), sep = ",", quote = FALSE, row.names = F)
```



## Step 2: Process 7-day-data

# Axivity

```{r Step 2 Axivity, echo=FALSE}
savedir.hip <- paste0(epochdir.hip, "/7d18h")
validday.axivity(epochdir = epochdir.hip, epochlength = 5, minhours = 18, mindays = 7, savedir = savedir.hip, data.castor, analysis = "reliability")
paste0("hip: accelerometer files that provide 7 days of at least 18 h: ", length(list.files(savedir.hip, pattern = ".RData")), "(", length(list.files(savedir.hip, pattern = ".RData"))/length(list.files(paste0(epochdir.hip, "/1d8h"), pattern = ".RData"))*100," %)")

savedir.wrist <- paste0(epochdir.wrist, "/7d18h")
validday.axivity(epochdir = epochdir.wrist, epochlength = 5, minhours = 18, mindays = 7, savedir = savedir.wrist, data.castor, analysis = "reliability") 
paste0("wrist: accelerometer files that provide 7 days of at least 18 h: ", length(list.files(savedir.wrist, pattern = ".RData")), "(", length(list.files(savedir.wrist, pattern = ".RData"))/length(list.files(paste0(epochdir.wrist, "/1d8h"), pattern = ".RData"))*100," %)")
## Generate the outcomes per accelerometer recording (per day)
axivity.estimates.hip <- estimates.axivity(savedir.hip) 
axivity.estimates.wrist <- estimates.axivity(savedir.wrist)
#axivity.estimates.hip <- estimates.axivity(savedir.hip, filter_sleep = TRUE) 
#axivity.estimates.wrist <- estimates.axivity(savedir.wrist, filter_sleep = TRUE)
```


```{r Step 3 Axivity, echo=FALSE}
library(dplyr)
## HIP
if(filter_sleep == TRUE){
  index <- axivity.estimates.hip$id[which(is.na(axivity.estimates.hip$ENMO))]
  axivity.estimates.hip <- axivity.estimates.hip[-which(axivity.estimates.hip$id %in% index),]
  index <- axivity.estimates.wrist$id[which(is.na(axivity.estimates.wrist$ENMO))]
  axivity.estimates.wrist <- axivity.estimates.wrist[-which(axivity.estimates.wrist$id %in% index),]
}

# IQR ENMO
quantile(axivity.estimates.hip$ENMO[which(axivity.estimates.hip$weekday == "1")], na.rm = TRUE)
quantile(axivity.estimates.hip$ENMO[which(axivity.estimates.hip$weekday == "0")], na.rm = TRUE)
quantile(axivity.estimates.hip$ENMO_25[which(axivity.estimates.hip$weekday == "1")], na.rm = TRUE)
quantile(axivity.estimates.hip$ENMO_25[which(axivity.estimates.hip$weekday == "0")], na.rm = TRUE)
quantile(axivity.estimates.hip$ENMO_75[which(axivity.estimates.hip$weekday == "1")], na.rm = TRUE)
quantile(axivity.estimates.hip$ENMO_75[which(axivity.estimates.hip$weekday == "0")], na.rm = TRUE)
quantile(axivity.estimates.hip$ENMO_25_duration[which(axivity.estimates.hip$weekday == "1")], na.rm = TRUE)
quantile(axivity.estimates.hip$ENMO_25_duration[which(axivity.estimates.hip$weekday == "0")], na.rm = TRUE)
quantile(axivity.estimates.hip$ENMO_50_duration[which(axivity.estimates.hip$weekday == "1")], na.rm = TRUE)
quantile(axivity.estimates.hip$ENMO_50_duration[which(axivity.estimates.hip$weekday == "0")], na.rm = TRUE)
quantile(axivity.estimates.hip$ENMO_75_duration[which(axivity.estimates.hip$weekday == "1")], na.rm = TRUE)
quantile(axivity.estimates.hip$ENMO_75_duration[which(axivity.estimates.hip$weekday == "0")], na.rm = TRUE)

# IQR MAD
quantile(axivity.estimates.hip$MAD[which(axivity.estimates.hip$weekday == "1")], na.rm = TRUE)
quantile(axivity.estimates.hip$MAD[which(axivity.estimates.hip$weekday == "0")], na.rm = TRUE)
quantile(axivity.estimates.hip$MAD_25[which(axivity.estimates.hip$weekday == "1")], na.rm = TRUE)
quantile(axivity.estimates.hip$MAD_25[which(axivity.estimates.hip$weekday == "0")], na.rm = TRUE)
quantile(axivity.estimates.hip$MAD_75[which(axivity.estimates.hip$weekday == "1")], na.rm = TRUE)
quantile(axivity.estimates.hip$MAD_75[which(axivity.estimates.hip$weekday == "0")], na.rm = TRUE)
quantile(axivity.estimates.hip$MAD_25_duration[which(axivity.estimates.hip$weekday == "1")], na.rm = TRUE)
quantile(axivity.estimates.hip$MAD_25_duration[which(axivity.estimates.hip$weekday == "0")], na.rm = TRUE)
quantile(axivity.estimates.hip$MAD_50_duration[which(axivity.estimates.hip$weekday == "1")], na.rm = TRUE)
quantile(axivity.estimates.hip$MAD_50_duration[which(axivity.estimates.hip$weekday == "0")], na.rm = TRUE)
quantile(axivity.estimates.hip$MAD_75_duration[which(axivity.estimates.hip$weekday == "1")], na.rm = TRUE)
quantile(axivity.estimates.hip$MAD_75_duration[which(axivity.estimates.hip$weekday == "0")], na.rm = TRUE)

res_ENMO.hip <- wilcox.test(ENMO ~ weekday, data = axivity.estimates.hip, paired = FALSE)
z_ENMO.hip <- qnorm(res_ENMO.hip$p.value/2)
paste0("hip ENMO: Zscore =" ,z_ENMO.hip, ", p-value = ", res_ENMO.hip$p.value)
res_ENMO_25.hip <- wilcox.test(ENMO_25 ~ weekday, data = axivity.estimates.hip, paired = FALSE)
z_ENMO_25.hip <- qnorm(res_ENMO_25.hip$p.value/2)
paste0("hip ENMO 25: Zscore =" ,z_ENMO_25.hip, ", p-value = ", res_ENMO_25.hip$p.value)
res_ENMO_75.hip <- wilcox.test(ENMO_75 ~ weekday, data = axivity.estimates.hip, paired = FALSE)
z_ENMO_75.hip <- qnorm(res_ENMO_75.hip$p.value/2)
paste0("hip ENMO 75: Zscore =" ,z_ENMO_75.hip, ", p-value = ", res_ENMO_75.hip$p.value)

res_ENMO_25_dur.hip <- wilcox.test(ENMO_25_duration ~ weekday, data = axivity.estimates.hip, paired = FALSE)
z_ENMO_25_dur.hip <- qnorm(res_ENMO_25_dur.hip$p.value/2)
paste0("hip ENMO 25 dur: Zscore =" ,z_ENMO_25_dur.hip, ", p-value = ", res_ENMO_25_dur.hip$p.value)
res_ENMO_50_dur.hip <- wilcox.test(ENMO_50_duration ~ weekday, data = axivity.estimates.hip, paired = FALSE)
z_ENMO_50_dur.hip <- qnorm(res_ENMO_50_dur.hip$p.value/2)
paste0("hip ENMO 50 dur: Zscore =" ,z_ENMO_50_dur.hip, ", p-value = ", res_ENMO_50_dur.hip$p.value)
res_ENMO_75_dur.hip <- wilcox.test(ENMO_75_duration ~ weekday, data = axivity.estimates.hip, paired = FALSE)
z_ENMO_75_dur.hip <- qnorm(res_ENMO_75_dur.hip$p.value/2)
paste0("hip ENMO 75 dur: Zscore =" ,z_ENMO_75_dur.hip, ", p-value = ", res_ENMO_75_dur.hip$p.value)

res_MAD.hip <- wilcox.test(MAD ~ weekday, data = axivity.estimates.hip, paired = FALSE)
z_MAD.hip <- qnorm(res_MAD.hip$p.value/2)
paste0("hip MAD: Zscore =" ,z_MAD.hip, ", p-value = ", res_MAD.hip$p.value)
res_MAD_25.hip <- wilcox.test(MAD_25 ~ weekday, data = axivity.estimates.hip, paired = FALSE)
z_MAD_25.hip <- qnorm(res_MAD_25.hip$p.value/2)
paste0("hip MAD 25: Zscore =" ,z_MAD_25.hip, ", p-value = ", res_MAD_25.hip$p.value)
res_MAD_75.hip <- wilcox.test(MAD_75 ~ weekday, data = axivity.estimates.hip, paired = FALSE)
z_MAD_75.hip <- qnorm(res_MAD_75.hip$p.value/2)
paste0("hip MAD 75: Zscore =" ,z_MAD_75.hip, ", p-value = ", res_MAD_75.hip$p.value)

res_MAD_25_dur.hip <- wilcox.test(MAD_25_duration ~ weekday, data = axivity.estimates.hip, paired = FALSE)
z_MAD_25_dur.hip <- qnorm(res_MAD_25_dur.hip$p.value/2)
paste0("hip MAD 25 dur: Zscore =" ,z_MAD_25_dur.hip, ", p-value = ", res_MAD_25_dur.hip$p.value)
res_MAD_50_dur.hip <- wilcox.test(MAD_50_duration ~ weekday, data = axivity.estimates.hip, paired = FALSE)
z_MAD_50_dur.hip <- qnorm(res_MAD_50_dur.hip$p.value/2)
paste0("hip MAD 50 dur: Zscore =" ,z_MAD_50_dur.hip, ", p-value = ", res_MAD_50_dur.hip$p.value)
res_MAD_75_dur.hip <- wilcox.test(MAD_75_duration ~ weekday, data = axivity.estimates.hip, paired = FALSE)
z_MAD_75_dur.hip <- qnorm(res_MAD_75_dur.hip$p.value/2)
paste0("hip MAD 75 dur: Zscore =" ,z_MAD_75_dur.hip, ", p-value = ", res_MAD_75_dur.hip$p.value)

## WRIST
# IQR ENMO
quantile(axivity.estimates.wrist$ENMO[which(axivity.estimates.wrist$weekday == "1")], na.rm = TRUE)
quantile(axivity.estimates.wrist$ENMO[which(axivity.estimates.wrist$weekday == "0")], na.rm = TRUE)
quantile(axivity.estimates.wrist$ENMO_25[which(axivity.estimates.wrist$weekday == "1")], na.rm = TRUE)
quantile(axivity.estimates.wrist$ENMO_25[which(axivity.estimates.wrist$weekday == "0")], na.rm = TRUE)
quantile(axivity.estimates.wrist$ENMO_75[which(axivity.estimates.wrist$weekday == "1")], na.rm = TRUE)
quantile(axivity.estimates.wrist$ENMO_75[which(axivity.estimates.wrist$weekday == "0")], na.rm = TRUE)
quantile(axivity.estimates.wrist$ENMO_25_duration[which(axivity.estimates.wrist$weekday == "1")], na.rm = TRUE)
quantile(axivity.estimates.wrist$ENMO_25_duration[which(axivity.estimates.wrist$weekday == "0")], na.rm = TRUE)
quantile(axivity.estimates.wrist$ENMO_50_duration[which(axivity.estimates.wrist$weekday == "1")], na.rm = TRUE)
quantile(axivity.estimates.wrist$ENMO_50_duration[which(axivity.estimates.wrist$weekday == "0")], na.rm = TRUE)
quantile(axivity.estimates.wrist$ENMO_75_duration[which(axivity.estimates.wrist$weekday == "1")], na.rm = TRUE)
quantile(axivity.estimates.wrist$ENMO_75_duration[which(axivity.estimates.wrist$weekday == "0")], na.rm = TRUE)

# IQR MAD
quantile(axivity.estimates.wrist$MAD[which(axivity.estimates.wrist$weekday == "1")], na.rm = TRUE)
quantile(axivity.estimates.wrist$MAD[which(axivity.estimates.wrist$weekday == "0")], na.rm = TRUE)
quantile(axivity.estimates.wrist$MAD_25[which(axivity.estimates.wrist$weekday == "1")], na.rm = TRUE)
quantile(axivity.estimates.wrist$MAD_25[which(axivity.estimates.wrist$weekday == "0")], na.rm = TRUE)
quantile(axivity.estimates.wrist$MAD_75[which(axivity.estimates.wrist$weekday == "1")], na.rm = TRUE)
quantile(axivity.estimates.wrist$MAD_75[which(axivity.estimates.wrist$weekday == "0")], na.rm = TRUE)
quantile(axivity.estimates.wrist$MAD_25_duration[which(axivity.estimates.wrist$weekday == "1")], na.rm = TRUE)
quantile(axivity.estimates.wrist$MAD_25_duration[which(axivity.estimates.wrist$weekday == "0")], na.rm = TRUE)
quantile(axivity.estimates.wrist$MAD_50_duration[which(axivity.estimates.wrist$weekday == "1")], na.rm = TRUE)
quantile(axivity.estimates.wrist$MAD_50_duration[which(axivity.estimates.wrist$weekday == "0")], na.rm = TRUE)
quantile(axivity.estimates.wrist$MAD_75_duration[which(axivity.estimates.wrist$weekday == "1")], na.rm = TRUE)
quantile(axivity.estimates.wrist$MAD_75_duration[which(axivity.estimates.wrist$weekday == "0")], na.rm = TRUE)

res_ENMO.wrist <- wilcox.test(ENMO ~ weekday, data = axivity.estimates.wrist, paired = FALSE)
z_ENMO.wrist <- qnorm(res_ENMO.wrist$p.value/2)
paste0("wrist ENMO: Zscore =" ,z_ENMO.wrist, ", p-value = ", res_ENMO.wrist$p.value)
res_ENMO_25.wrist <- wilcox.test(ENMO_25 ~ weekday, data = axivity.estimates.wrist, paired = FALSE)
z_ENMO_25.wrist <- qnorm(res_ENMO_25.wrist$p.value/2)
paste0("wrist ENMO 25: Zscore =" ,z_ENMO_25.wrist, ", p-value = ", res_ENMO_25.wrist$p.value)
res_ENMO_75.wrist <- wilcox.test(ENMO_75 ~ weekday, data = axivity.estimates.wrist, paired = FALSE)
z_ENMO_75.wrist <- qnorm(res_ENMO_75.wrist$p.value/2)
paste0("wrist ENMO 75: Zscore =" ,z_ENMO_75.wrist, ", p-value = ", res_ENMO_75.wrist$p.value)

res_ENMO_25_dur.wrist <- wilcox.test(ENMO_25_duration ~ weekday, data = axivity.estimates.wrist, paired = FALSE)
z_ENMO_25_dur.wrist <- qnorm(res_ENMO_25_dur.wrist$p.value/2)
paste0("wrist ENMO 25 dur : Zscore =" ,z_ENMO_25_dur.wrist, ", p-value = ", res_ENMO_25_dur.wrist$p.value)
res_ENMO_50_dur.wrist <- wilcox.test(ENMO_50_duration ~ weekday, data = axivity.estimates.wrist, paired = FALSE)
z_ENMO_50_dur.wrist <- qnorm(res_ENMO_50_dur.wrist$p.value/2)
paste0("wrist ENMO 50 dur: Zscore =" ,z_ENMO_50_dur.wrist, ", p-value = ", res_ENMO_50_dur.wrist$p.value)
res_ENMO_75_dur.wrist <- wilcox.test(ENMO_75_duration ~ weekday, data = axivity.estimates.wrist, paired = FALSE)
z_ENMO_75_dur.wrist <- qnorm(res_ENMO_75_dur.wrist$p.value/2)
paste0("wrist ENMO 75 dur: Zscore =" ,z_ENMO_75_dur.wrist, ", p-value = ", res_ENMO_75_dur.wrist$p.value)

res_MAD.wrist <- wilcox.test(MAD ~ weekday, data = axivity.estimates.wrist, paired = FALSE)
z_MAD.wrist <- qnorm(res_MAD.wrist$p.value/2)
paste0("wrist MAD: Zscore =" ,z_MAD.wrist, ", p-value = ", res_MAD.wrist$p.value)
res_MAD_25.wrist <- wilcox.test(MAD_25 ~ weekday, data = axivity.estimates.wrist, paired = FALSE)
z_MAD_25.wrist <- qnorm(res_MAD_25.wrist$p.value/2)
paste0("wrist MAD 25: Zscore =" ,z_MAD_25.wrist, ", p-value = ", res_MAD_25.wrist$p.value)
res_MAD_75.wrist <- wilcox.test(MAD_75 ~ weekday, data = axivity.estimates.wrist, paired = FALSE)
z_MAD_75.wrist <- qnorm(res_MAD_75.wrist$p.value/2)
paste0("wrist MAD 75: Zscore =" ,z_MAD_75.wrist, ", p-value = ", res_MAD_75.wrist$p.value)

res_MAD_25_dur.wrist <- wilcox.test(MAD_25_duration ~ weekday, data = axivity.estimates.wrist, paired = FALSE)
z_MAD_25_dur.wrist <- qnorm(res_MAD_25_dur.wrist$p.value/2)
paste0("wrist MAD 25 dur: Zscore =" ,z_MAD_25_dur.wrist, ", p-value = ", res_MAD_25_dur.wrist$p.value)
res_MAD_50_dur.wrist <- wilcox.test(MAD_50_duration ~ weekday, data = axivity.estimates.wrist, paired = FALSE)
z_MAD_50_dur.wrist <- qnorm(res_MAD_50_dur.wrist$p.value/2)
paste0("wrist MAD 50 dur: Zscore =" ,z_MAD_50_dur.wrist, ", p-value = ", res_MAD_50_dur.wrist$p.value)
res_MAD_75_dur.wrist <- wilcox.test(MAD_75_duration ~ weekday, data = axivity.estimates.wrist, paired = FALSE)
z_MAD_75_dur.wrist <- qnorm(res_MAD_75_dur.wrist$p.value/2)
paste0("wrist MAD 75 dur: Zscore =" ,z_MAD_75_dur.wrist, ", p-value = ", res_MAD_75_dur.wrist$p.value)

rm(res_ENMO.hip, z_ENMO.hip, res_ENMO_25.hip, z_ENMO_25.hip, res_ENMO_75.hip, z_ENMO_75.hip,
   res_ENMO_25_dur.hip, z_ENMO_25_dur.hip, res_ENMO_50_dur.hip, z_ENMO_50_dur.hip, res_ENMO_75_dur.hip, z_ENMO_75_dur.hip,
   res_MAD.hip, z_MAD.hip, res_MAD_25.hip, z_MAD_25.hip, res_MAD_75.hip, z_MAD_75.hip, 
   res_MAD_25_dur.hip, z_MAD_25_dur.hip, res_MAD_50_dur.hip, z_MAD_50_dur.hip, res_MAD_75_dur.hip, z_MAD_75_dur.hip, 
   res_ENMO.wrist, z_ENMO.wrist, res_ENMO_25.wrist, z_ENMO_25.wrist, res_ENMO_75.wrist, z_ENMO_75.wrist,
   res_ENMO_25_dur.wrist, z_ENMO_25_dur.wrist, res_ENMO_50_dur.wrist, z_ENMO_50_dur.wrist, res_ENMO_75_dur.wrist, z_ENMO_75_dur.wrist,
   res_MAD.wrist, z_MAD.wrist, res_MAD_25.wrist, z_MAD_25.wrist, res_MAD_75.wrist, z_MAD_75.wrist, 
   res_MAD_25_dur.wrist, z_MAD_25_dur.wrist, res_MAD_50_dur.wrist, z_MAD_50_dur.wrist, res_MAD_75_dur.wrist, z_MAD_75_dur.wrist)
```

```{r Step 3 Axivity per milestone, echo=FALSE}
library(dplyr)
## Hip
# Not walking
desc.weekend.hip_notwalk <- group_by(estimates.notwalk.hip, weekday) %>% 
  summarise_at(c("ENMO", "MAD"),
               list(median = median, IQR = quantile), na.rm = TRUE)
desc.weekend.hip_notwalk[c(2,4,7,9),]

res_ENMO.hip <- wilcox.test(ENMO ~ weekday, data = estimates.notwalk.hip, paired = FALSE)
z_ENMO.hip <- qnorm(res_ENMO.hip$p.value/2)
paste0("hip not walking ENMO: Zscore =" ,z_ENMO.hip, ", p-value = ", res_ENMO.hip$p.value)
res_MAD.hip <- wilcox.test(MAD ~ weekday, data = estimates.notwalk.hip, paired = FALSE)
z_MAD.hip <- qnorm(res_MAD.hip$p.value/2)
paste0("hip not walking MAD: Zscore =" ,z_MAD.hip, ", p-value = ", res_MAD.hip$p.value)

# Walking
desc.weekend.hip_walk <- group_by(estimates.walk.hip, weekday) %>% 
  summarise_at(c("ENMO", "MAD"),
               list(median = median, IQR = quantile), na.rm = TRUE)
desc.weekend.hip_walk[c(2,4,7,9),]

res_ENMO.hip <- wilcox.test(ENMO ~ weekday, data = estimates.walk.hip, paired = FALSE)
z_ENMO.hip <- qnorm(res_ENMO.hip$p.value/2)
paste0("hip walking ENMO: Zscore =" ,z_ENMO.hip, ", p-value = ", res_ENMO.hip$p.value)
res_MAD.hip <- wilcox.test(MAD ~ weekday, data = estimates.walk.hip, paired = FALSE)
z_MAD.hip <- qnorm(res_MAD.hip$p.value/2)
paste0("hip walking MAD: Zscore =" ,z_MAD.hip, ", p-value = ", res_MAD.hip$p.value)

## Wrist
# Not walking
desc.weekend.wrist_notwalk <- group_by(estimates.notwalk.wrist, weekday) %>% 
  summarise_at(c("ENMO", "MAD"),
               list(median = median, IQR = quantile), na.rm = TRUE)
desc.weekend.wrist_notwalk[c(2,4,7,9),]

res_ENMO.wrist <- wilcox.test(ENMO ~ weekday, data = estimates.notwalk.wrist, paired = FALSE)
z_ENMO.wrist <- qnorm(res_ENMO.wrist$p.value/2)
paste0("wrist not walking ENMO: Zscore =" ,z_ENMO.wrist, ", p-value = ", res_ENMO.wrist$p.value)
res_MAD.wrist <- wilcox.test(MAD ~ weekday, data = estimates.notwalk.wrist, paired = FALSE)
z_MAD.wrist <- qnorm(res_MAD.wrist$p.value/2)
paste0("wrist not walking MAD: Zscore =" ,z_MAD.wrist, ", p-value = ", res_MAD.wrist$p.value)

# Walking
desc.weekend.wrist_walk <- group_by(estimates.walk.wrist, weekday) %>% 
  summarise_at(c("ENMO", "MAD"),
               list(median = median, IQR = quantile), na.rm = TRUE)
desc.weekend.wrist_walk[c(2,4,7,9),]

res_ENMO.wrist <- wilcox.test(ENMO ~ weekday, data = estimates.walk.wrist, paired = FALSE)
z_ENMO.wrist <- qnorm(res_ENMO.wrist$p.value/2)
paste0("wrist walking ENMO: Zscore =" ,z_ENMO.wrist, ", p-value = ", res_ENMO.wrist$p.value)
res_MAD.wrist <- wilcox.test(MAD ~ weekday, data = estimates.walk.wrist, paired = FALSE)
z_MAD.wrist <- qnorm(res_MAD.wrist$p.value/2)
paste0("wrist walking MAD: Zscore =" ,z_MAD.wrist, ", p-value = ", res_MAD.wrist$p.value)

# Both
desc.weekend.both_notwalk <- group_by(estimates.notwalk.both, weekday) %>% 
  summarise_at(c("ENMO.both", "MAD.both"),
               list(median = median, IQR = quantile), na.rm = TRUE)
desc.weekend.both_notwalk[c(2,4,7,9),]

res_ENMO.both <- wilcox.test(ENMO.both ~ weekday, data = estimates.notwalk.both, paired = FALSE)
z_ENMO.both <- qnorm(res_ENMO.both$p.value/2)
paste0("hip*wrist not walking ENMO: Zscore =" ,z_ENMO.both, ", p-value = ", res_ENMO.both$p.value)
res_MAD.both <- wilcox.test(MAD.both ~ weekday, data = estimates.notwalk.both, paired = FALSE)
z_MAD.both <- qnorm(res_MAD.both$p.value/2)
paste0("hip*wrist not walking MAD: Zscore =" ,z_MAD.both, ", p-value = ", res_MAD.both$p.value)

desc.weekend.both_walk <- group_by(estimates.walk.both, weekday) %>% 
  summarise_at(c("ENMO.both", "MAD.both"),
               list(median = median, IQR = quantile), na.rm = TRUE)
desc.weekend.both_walk[c(2,4,7,9),]

res_ENMO.both <- wilcox.test(ENMO.both ~ weekday, data = estimates.walk.both, paired = FALSE)
z_ENMO.both <- qnorm(res_ENMO.both$p.value/2)
paste0("hip*wrist walking ENMO: Zscore =" ,z_ENMO.both, ", p-value = ", res_ENMO.both$p.value)
res_MAD.both <- wilcox.test(MAD.both ~ weekday, data = estimates.walk.both, paired = FALSE)
z_MAD.both <- qnorm(res_MAD.both$p.value/2)
paste0("hip*wrist walking MAD: Zscore =" ,z_MAD.both, ", p-value = ", res_MAD.both$p.value)

rm(desc.weekend.hip, res_ENMO.hip, z_ENMO.hip, res_MAD.hip, z_MAD.hip, desc.weekend.wrist, res_ENMO.wrist, z_ENMO.wrist, res_MAD.wrist, z_MAD.wrist, desc.weekend.both, res_ENMO.both, z_ENMO.both, res_MAD.both, z_MAD.both)
```



## Step 4: Examine day-to-day variability

# Axivity
```{r Step 4 Axivity, echo=FALSE}
## Step 4: Day-to-day variability
# Hip
day_day_ENMO.hip <- friedman.test(y = axivity.estimates.hip$ENMO, groups = axivity.estimates.hip$days, blocks = axivity.estimates.hip$id)
paste0("Hip ENMO: Chi-square =" , day_day_ENMO.hip$statistic, ", p-value = ", day_day_ENMO.hip$p.value)
day_day_ENMO_25.hip <- friedman.test(y = axivity.estimates.hip$ENMO_25, groups = axivity.estimates.hip$days, blocks = axivity.estimates.hip$id)
paste0("Hip ENMO 25: Chi-square =" , day_day_ENMO_25.hip$statistic, ", p-value = ", day_day_ENMO_25.hip$p.value)
day_day_ENMO_75.hip <- friedman.test(y = axivity.estimates.hip$ENMO_75, groups = axivity.estimates.hip$days, blocks = axivity.estimates.hip$id)
paste0("Hip ENMO 75: Chi-square =" , day_day_ENMO_75.hip$statistic, ", p-value = ", day_day_ENMO_75.hip$p.value)
day_day_ENMO_25_dur.hip <- friedman.test(y = axivity.estimates.hip$ENMO_25_duration, groups = axivity.estimates.hip$days, blocks = axivity.estimates.hip$id)
paste0("Hip ENMO 25 dur: Chi-square =" , day_day_ENMO_25_dur.hip$statistic, ", p-value = ", day_day_ENMO_25_dur.hip$p.value)
day_day_ENMO_50_dur.hip <- friedman.test(y = axivity.estimates.hip$ENMO_50_duration, groups = axivity.estimates.hip$days, blocks = axivity.estimates.hip$id)
paste0("Hip ENMO 50 dur: Chi-square =" , day_day_ENMO_50_dur.hip$statistic, ", p-value = ", day_day_ENMO_50_dur.hip$p.value)
day_day_ENMO_75_dur.hip <- friedman.test(y = axivity.estimates.hip$ENMO_75_duration, groups = axivity.estimates.hip$days, blocks = axivity.estimates.hip$id)
paste0("Hip ENMO 75 dur: Chi-square =" , day_day_ENMO_75_dur.hip$statistic, ", p-value = ", day_day_ENMO_75_dur.hip$p.value)

day_day_MAD.hip <- friedman.test(y = axivity.estimates.hip$MAD, groups = axivity.estimates.hip$days, blocks = axivity.estimates.hip$id)
paste0("Hip MAD: Chi-square =" , day_day_MAD.hip$statistic, ", p-value = ", day_day_MAD.hip$p.value)
day_day_MAD_25.hip <- friedman.test(y = axivity.estimates.hip$MAD_25, groups = axivity.estimates.hip$days, blocks = axivity.estimates.hip$id)
paste0("Hip MAD 25: Chi-square =" , day_day_MAD_25.hip$statistic, ", p-value = ", day_day_MAD_25.hip$p.value)
day_day_MAD_75.hip <- friedman.test(y = axivity.estimates.hip$MAD_75, groups = axivity.estimates.hip$days, blocks = axivity.estimates.hip$id)
paste0("Hip MAD 75: Chi-square =" , day_day_MAD_75.hip$statistic, ", p-value = ", day_day_MAD_75.hip$p.value)
day_day_MAD_25_dur.hip <- friedman.test(y = axivity.estimates.hip$MAD_25_duration, groups = axivity.estimates.hip$days, blocks = axivity.estimates.hip$id)
paste0("Hip MAD 25 dur: Chi-square =" , day_day_MAD_25_dur.hip$statistic, ", p-value = ", day_day_MAD_25_dur.hip$p.value)
day_day_MAD_50_dur.hip <- friedman.test(y = axivity.estimates.hip$MAD_50_duration, groups = axivity.estimates.hip$days, blocks = axivity.estimates.hip$id)
paste0("Hip MAD 50 dur: Chi-square =" , day_day_MAD_50_dur.hip$statistic, ", p-value = ", day_day_MAD_50_dur.hip$p.value)
day_day_MAD_75_dur.hip <- friedman.test(y = axivity.estimates.hip$MAD_75_duration, groups = axivity.estimates.hip$days, blocks = axivity.estimates.hip$id)
paste0("Hip MAD 75 dur: Chi-square =" , day_day_MAD_75_dur.hip$statistic, ", p-value = ", day_day_MAD_75_dur.hip$p.value)

# Wrist
day_day_ENMO.wrist <- friedman.test(y = axivity.estimates.wrist$ENMO, groups = axivity.estimates.wrist$days, blocks = axivity.estimates.wrist$id)
paste0("wrist ENMO: Chi-square =" , day_day_ENMO.wrist$statistic, ", p-value = ", day_day_ENMO.wrist$p.value)
day_day_ENMO_25.wrist <- friedman.test(y = axivity.estimates.wrist$ENMO_25, groups = axivity.estimates.wrist$days, blocks = axivity.estimates.wrist$id)
paste0("wrist ENMO 25: Chi-square =" , day_day_ENMO_25.wrist$statistic, ", p-value = ", day_day_ENMO_25.wrist$p.value)
day_day_ENMO_75.wrist <- friedman.test(y = axivity.estimates.wrist$ENMO_75, groups = axivity.estimates.wrist$days, blocks = axivity.estimates.wrist$id)
paste0("wrist ENMO 75: Chi-square =" , day_day_ENMO_75.wrist$statistic, ", p-value = ", day_day_ENMO_75.wrist$p.value)
day_day_ENMO_25_dur.wrist <- friedman.test(y = axivity.estimates.wrist$ENMO_25_duration, groups = axivity.estimates.wrist$days, blocks = axivity.estimates.wrist$id)
paste0("wrist ENMO 25 dur: Chi-square =" , day_day_ENMO_25_dur.wrist$statistic, ", p-value = ", day_day_ENMO_25_dur.wrist$p.value)
day_day_ENMO_50_dur.wrist <- friedman.test(y = axivity.estimates.wrist$ENMO_50_duration, groups = axivity.estimates.wrist$days, blocks = axivity.estimates.wrist$id)
paste0("wrist ENMO 50 dur: Chi-square =" , day_day_ENMO_50_dur.wrist$statistic, ", p-value = ", day_day_ENMO_50_dur.wrist$p.value)
day_day_ENMO_75_dur.wrist <- friedman.test(y = axivity.estimates.wrist$ENMO_75_duration, groups = axivity.estimates.wrist$days, blocks = axivity.estimates.wrist$id)
paste0("wrist ENMO 75 dur: Chi-square =" , day_day_ENMO_75_dur.wrist$statistic, ", p-value = ", day_day_ENMO_75_dur.wrist$p.value)

day_day_MAD.wrist <- friedman.test(y = axivity.estimates.wrist$MAD, groups = axivity.estimates.wrist$days, blocks = axivity.estimates.wrist$id)
paste0("wrist MAD: Chi-square =" , day_day_MAD.wrist$statistic, ", p-value = ", day_day_MAD.wrist$p.value)
day_day_MAD_25.wrist <- friedman.test(y = axivity.estimates.wrist$MAD_25, groups = axivity.estimates.wrist$days, blocks = axivity.estimates.wrist$id)
paste0("wrist MAD 25: Chi-square =" , day_day_MAD_25.wrist$statistic, ", p-value = ", day_day_MAD_25.wrist$p.value)
day_day_MAD_75.wrist <- friedman.test(y = axivity.estimates.wrist$MAD_75, groups = axivity.estimates.wrist$days, blocks = axivity.estimates.wrist$id)
paste0("wrist MAD 75: Chi-square =" , day_day_MAD_75.wrist$statistic, ", p-value = ", day_day_MAD_75.wrist$p.value)
day_day_MAD_25_dur.wrist <- friedman.test(y = axivity.estimates.wrist$MAD_25_duration, groups = axivity.estimates.wrist$days, blocks = axivity.estimates.wrist$id)
paste0("wrist MAD 25 dur: Chi-square =" , day_day_MAD_25_dur.wrist$statistic, ", p-value = ", day_day_MAD_25_dur.wrist$p.value)
day_day_MAD_50_dur.wrist <- friedman.test(y = axivity.estimates.wrist$MAD_50_duration, groups = axivity.estimates.wrist$days, blocks = axivity.estimates.wrist$id)
paste0("wrist MAD 50 dur: Chi-square =" , day_day_MAD_50_dur.wrist$statistic, ", p-value = ", day_day_MAD_50_dur.wrist$p.value)
day_day_MAD_75_dur.wrist <- friedman.test(y = axivity.estimates.wrist$MAD_75_duration, groups = axivity.estimates.wrist$days, blocks = axivity.estimates.wrist$id)
paste0("wrist MAD 75 dur: Chi-square =" , day_day_MAD_75_dur.wrist$statistic, ", p-value = ", day_day_MAD_75_dur.wrist$p.value)

```

## Step 5: Calculate single day intraclass correlation (ICC) (2,1)

# Axivity
```{r Step 5 Axivity, echo=FALSE}
# Run intra-class correlations (ICC). Random consistency models, using single measure, ICC(2,1). Single measure is ICC for single day.
# Hip
ratings.hip  <- reshape(axivity.estimates.hip, idvar = "days", timevar = "id", direction = "wide")

ratings_ENMO.hip_long <- as.data.frame(cbind(axivity.estimates.hip$id, axivity.estimates.hip$days, axivity.estimates.hip$ENMO))
names(ratings_ENMO.hip_long) <- c("id", "days", "ENMO")
ratings_ENMO.hip_long$ENMO <- as.numeric(ratings_ENMO.hip_long$ENMO)
ratings_ENMO.hip  <- reshape(ratings_ENMO.hip_long, idvar = "days", timevar = "id", direction = "wide")
ICC.ENMO.hip <- irr::icc(ratings_ENMO.hip[,-1], model = "twoway", type = "consistency")
ratings_ENMO_25.hip_long <- as.data.frame(cbind(axivity.estimates.hip$id, axivity.estimates.hip$days, axivity.estimates.hip$ENMO_25))
names(ratings_ENMO_25.hip_long) <- c("id", "days", "ENMO")
ratings_ENMO_25.hip_long$ENMO <- as.numeric(ratings_ENMO_25.hip_long$ENMO)
ratings_ENMO_25.hip  <- reshape(ratings_ENMO_25.hip_long, idvar = "days", timevar = "id", direction = "wide")
ICC.ENMO_25.hip <- irr::icc(ratings_ENMO_25.hip[,-1], model = "twoway", type = "consistency")
ratings_ENMO_75.hip_long <- as.data.frame(cbind(axivity.estimates.hip$id, axivity.estimates.hip$days, axivity.estimates.hip$ENMO_75))
names(ratings_ENMO_75.hip_long) <- c("id", "days", "ENMO")
ratings_ENMO_75.hip_long$ENMO <- as.numeric(ratings_ENMO_75.hip_long$ENMO)
ratings_ENMO_75.hip  <- reshape(ratings_ENMO_75.hip_long, idvar = "days", timevar = "id", direction = "wide")
ICC.ENMO_75.hip <- irr::icc(ratings_ENMO_75.hip[,-1], model = "twoway", type = "consistency")

ratings_ENMO_25_dur.hip_long <- as.data.frame(cbind(axivity.estimates.hip$id, axivity.estimates.hip$days, axivity.estimates.hip$ENMO_25_duration))
names(ratings_ENMO_25_dur.hip_long) <- c("id", "days", "ENMO")
ratings_ENMO_25_dur.hip_long$ENMO <- as.numeric(ratings_ENMO_25_dur.hip_long$ENMO)
ratings_ENMO_25_dur.hip  <- reshape(ratings_ENMO_25_dur.hip_long, idvar = "days", timevar = "id", direction = "wide")
ICC.ENMO_25_dur.hip <- irr::icc(ratings_ENMO_25_dur.hip[,-1], model = "twoway", type = "consistency")
ratings_ENMO_50_dur.hip_long <- as.data.frame(cbind(axivity.estimates.hip$id, axivity.estimates.hip$days, axivity.estimates.hip$ENMO_50_duration))
names(ratings_ENMO_50_dur.hip_long) <- c("id", "days", "ENMO")
ratings_ENMO_50_dur.hip_long$ENMO <- as.numeric(ratings_ENMO_50_dur.hip_long$ENMO)
ratings_ENMO_50_dur.hip  <- reshape(ratings_ENMO_50_dur.hip_long, idvar = "days", timevar = "id", direction = "wide")
ICC.ENMO_50_dur.hip <- irr::icc(ratings_ENMO_50_dur.hip[,-1], model = "twoway", type = "consistency")
ratings_ENMO_75_dur.hip_long <- as.data.frame(cbind(axivity.estimates.hip$id, axivity.estimates.hip$days, axivity.estimates.hip$ENMO_75_duration))
names(ratings_ENMO_75_dur.hip_long) <- c("id", "days", "ENMO")
ratings_ENMO_75_dur.hip_long$ENMO <- as.numeric(ratings_ENMO_75_dur.hip_long$ENMO)
ratings_ENMO_75_dur.hip  <- reshape(ratings_ENMO_75_dur.hip_long, idvar = "days", timevar = "id", direction = "wide")
ICC.ENMO_75_dur.hip <- irr::icc(ratings_ENMO_75_dur.hip[,-1], model = "twoway", type = "consistency")

ratings_MAD.hip_long <- as.data.frame(cbind(axivity.estimates.hip$id, axivity.estimates.hip$days, axivity.estimates.hip$MAD))
names(ratings_MAD.hip_long) <- c("id", "days", "MAD")
ratings_MAD.hip_long$MAD <- as.numeric(ratings_MAD.hip_long$MAD)
ratings_MAD.hip  <- reshape(ratings_MAD.hip_long, idvar = "days", timevar = "id", direction = "wide")
ICC.MAD.hip <- irr::icc(ratings_MAD.hip[,-1], model = "twoway", type = "consistency")
ratings_MAD_25.hip_long <- as.data.frame(cbind(axivity.estimates.hip$id, axivity.estimates.hip$days, axivity.estimates.hip$MAD_25))
names(ratings_MAD_25.hip_long) <- c("id", "days", "MAD")
ratings_MAD_25.hip_long$MAD <- as.numeric(ratings_MAD_25.hip_long$MAD)
ratings_MAD_25.hip  <- reshape(ratings_MAD_25.hip_long, idvar = "days", timevar = "id", direction = "wide")
ICC.MAD_25.hip <- irr::icc(ratings_MAD_25.hip[,-1], model = "twoway", type = "consistency")
ratings_MAD_75.hip_long <- as.data.frame(cbind(axivity.estimates.hip$id, axivity.estimates.hip$days, axivity.estimates.hip$MAD_75))
names(ratings_MAD_75.hip_long) <- c("id", "days", "MAD")
ratings_MAD_75.hip_long$MAD <- as.numeric(ratings_MAD_75.hip_long$MAD)
ratings_MAD_75.hip  <- reshape(ratings_MAD_75.hip_long, idvar = "days", timevar = "id", direction = "wide")
ICC.MAD_75.hip <- irr::icc(ratings_MAD_75.hip[,-1], model = "twoway", type = "consistency")
ratings_MAD_25_dur.hip_long <- as.data.frame(cbind(axivity.estimates.hip$id, axivity.estimates.hip$days, axivity.estimates.hip$MAD_25_duration))
names(ratings_MAD_25_dur.hip_long) <- c("id", "days", "MAD")
ratings_MAD_25_dur.hip_long$MAD <- as.numeric(ratings_MAD_25_dur.hip_long$MAD)
ratings_MAD_25_dur.hip  <- reshape(ratings_MAD_25_dur.hip_long, idvar = "days", timevar = "id", direction = "wide")
ICC.MAD_25_dur.hip <- irr::icc(ratings_MAD_25_dur.hip[,-1], model = "twoway", type = "consistency")
ratings_MAD_50_dur.hip_long <- as.data.frame(cbind(axivity.estimates.hip$id, axivity.estimates.hip$days, axivity.estimates.hip$MAD_50_duration))
names(ratings_MAD_50_dur.hip_long) <- c("id", "days", "MAD")
ratings_MAD_50_dur.hip_long$MAD <- as.numeric(ratings_MAD_50_dur.hip_long$MAD)
ratings_MAD_50_dur.hip  <- reshape(ratings_MAD_50_dur.hip_long, idvar = "days", timevar = "id", direction = "wide")
ICC.MAD_50_dur.hip <- irr::icc(ratings_MAD_50_dur.hip[,-1], model = "twoway", type = "consistency")
ratings_MAD_75_dur.hip_long <- as.data.frame(cbind(axivity.estimates.hip$id, axivity.estimates.hip$days, axivity.estimates.hip$MAD_75_duration))
names(ratings_MAD_75_dur.hip_long) <- c("id", "days", "MAD")
ratings_MAD_75_dur.hip_long$MAD <- as.numeric(ratings_MAD_75_dur.hip_long$MAD)
ratings_MAD_75_dur.hip  <- reshape(ratings_MAD_75_dur.hip_long, idvar = "days", timevar = "id", direction = "wide")
ICC.MAD_75_dur.hip <- irr::icc(ratings_MAD_75_dur.hip[,-1], model = "twoway", type = "consistency")

paste0("Hip ENMO: ICC =" , ICC.ENMO.hip$value, "[", ICC.ENMO.hip$lbound, ";", ICC.ENMO.hip$ubound, "]")
paste0("Hip ENMO 25: ICC =" , ICC.ENMO_25.hip$value, "[", ICC.ENMO_25.hip$lbound, ";", ICC.ENMO_25.hip$ubound, "]")
paste0("Hip ENMO 75: ICC =" , ICC.ENMO_75.hip$value, "[", ICC.ENMO_75.hip$lbound, ";", ICC.ENMO_75.hip$ubound, "]")
paste0("Hip ENMO 25 dur: ICC =" , ICC.ENMO_25_dur.hip$value, "[", ICC.ENMO_25_dur.hip$lbound, ";", ICC.ENMO_25_dur.hip$ubound, "]")
paste0("Hip ENMO 50: ICC =" , ICC.ENMO_50_dur.hip$value, "[", ICC.ENMO_50_dur.hip$lbound, ";", ICC.ENMO_50_dur.hip$ubound, "]")
paste0("Hip ENMO 75: ICC =" , ICC.ENMO_75_dur.hip$value, "[", ICC.ENMO_75_dur.hip$lbound, ";", ICC.ENMO_75_dur.hip$ubound, "]")

paste0("Hip MAD: ICC =" , ICC.MAD.hip$value, "[", ICC.MAD.hip$lbound, ";", ICC.MAD.hip$ubound, "]")
#might add the other single day ICCs
paste0("Hip MAD 25: ICC =" , ICC.MAD_25.hip$value, "[", ICC.MAD_25.hip$lbound, ";", ICC.MAD_25.hip$ubound, "]")
paste0("Hip MAD 75: ICC =" , ICC.MAD_75.hip$value, "[", ICC.MAD_75.hip$lbound, ";", ICC.MAD_75.hip$ubound, "]")
paste0("Hip MAD 25 dur: ICC =" , ICC.MAD_25_dur.hip$value, "[", ICC.MAD_25_dur.hip$lbound, ";", ICC.MAD_25_dur.hip$ubound, "]")
paste0("Hip MAD 50 dur: ICC =" , ICC.MAD_50_dur.hip$value, "[", ICC.MAD_50_dur.hip$lbound, ";", ICC.MAD_50_dur.hip$ubound, "]")
paste0("Hip MAD 75 dur: ICC =" , ICC.MAD_75_dur.hip$value, "[", ICC.MAD_75_dur.hip$lbound, ";", ICC.MAD_75_dur.hip$ubound, "]")

# Wrist
ratings.wrist  <- reshape(axivity.estimates.wrist, idvar = "days", timevar = "id", direction = "wide")

ratings_ENMO.wrist_long <- as.data.frame(cbind(axivity.estimates.wrist$id, axivity.estimates.wrist$days, axivity.estimates.wrist$ENMO))
names(ratings_ENMO.wrist_long) <- c("id", "days", "ENMO")
ratings_ENMO.wrist_long$ENMO <- as.numeric(ratings_ENMO.wrist_long$ENMO)
ratings_ENMO.wrist  <- reshape(ratings_ENMO.wrist_long, idvar = "days", timevar = "id", direction = "wide")
ICC.ENMO.wrist <- irr::icc(ratings_ENMO.wrist[,-1], model = "twoway", type = "consistency")
ratings_ENMO_25.wrist_long <- as.data.frame(cbind(axivity.estimates.wrist$id, axivity.estimates.wrist$days, axivity.estimates.wrist$ENMO_25))
names(ratings_ENMO_25.wrist_long) <- c("id", "days", "ENMO")
ratings_ENMO_25.wrist_long$ENMO <- as.numeric(ratings_ENMO_25.wrist_long$ENMO)
ratings_ENMO_25.wrist  <- reshape(ratings_ENMO_25.wrist_long, idvar = "days", timevar = "id", direction = "wide")
ICC.ENMO_25.wrist <- irr::icc(ratings_ENMO_25.wrist[,-1], model = "twoway", type = "consistency")
ratings_ENMO_75.wrist_long <- as.data.frame(cbind(axivity.estimates.wrist$id, axivity.estimates.wrist$days, axivity.estimates.wrist$ENMO_75))
names(ratings_ENMO_75.wrist_long) <- c("id", "days", "ENMO")
ratings_ENMO_75.wrist_long$ENMO <- as.numeric(ratings_ENMO_75.wrist_long$ENMO)
ratings_ENMO_75.wrist  <- reshape(ratings_ENMO_75.wrist_long, idvar = "days", timevar = "id", direction = "wide")
ICC.ENMO_75.wrist <- irr::icc(ratings_ENMO_75.wrist[,-1], model = "twoway", type = "consistency")

ratings_ENMO_25_dur.wrist_long <- as.data.frame(cbind(axivity.estimates.wrist$id, axivity.estimates.wrist$days, axivity.estimates.wrist$ENMO_25_duration))
names(ratings_ENMO_25_dur.wrist_long) <- c("id", "days", "ENMO")
ratings_ENMO_25_dur.wrist_long$ENMO <- as.numeric(ratings_ENMO_25_dur.wrist_long$ENMO)
ratings_ENMO_25_dur.wrist  <- reshape(ratings_ENMO_25_dur.wrist_long, idvar = "days", timevar = "id", direction = "wide")
ICC.ENMO_25_dur.wrist <- irr::icc(ratings_ENMO_25_dur.wrist[,-1], model = "twoway", type = "consistency")
ratings_ENMO_50_dur.wrist_long <- as.data.frame(cbind(axivity.estimates.wrist$id, axivity.estimates.wrist$days, axivity.estimates.wrist$ENMO_50_duration))
names(ratings_ENMO_50_dur.wrist_long) <- c("id", "days", "ENMO")
ratings_ENMO_50_dur.wrist_long$ENMO <- as.numeric(ratings_ENMO_50_dur.wrist_long$ENMO)
ratings_ENMO_50_dur.wrist  <- reshape(ratings_ENMO_50_dur.wrist_long, idvar = "days", timevar = "id", direction = "wide")
ICC.ENMO_50_dur.wrist <- irr::icc(ratings_ENMO_50_dur.wrist[,-1], model = "twoway", type = "consistency")
ratings_ENMO_75_dur.wrist_long <- as.data.frame(cbind(axivity.estimates.wrist$id, axivity.estimates.wrist$days, axivity.estimates.wrist$ENMO_75_duration))
names(ratings_ENMO_75_dur.wrist_long) <- c("id", "days", "ENMO")
ratings_ENMO_75_dur.wrist_long$ENMO <- as.numeric(ratings_ENMO_75_dur.wrist_long$ENMO)
ratings_ENMO_75_dur.wrist  <- reshape(ratings_ENMO_75_dur.wrist_long, idvar = "days", timevar = "id", direction = "wide")
ICC.ENMO_75_dur.wrist <- irr::icc(ratings_ENMO_75_dur.wrist[,-1], model = "twoway", type = "consistency")

ratings_MAD.wrist_long <- as.data.frame(cbind(axivity.estimates.wrist$id, axivity.estimates.wrist$days, axivity.estimates.wrist$MAD))
names(ratings_MAD.wrist_long) <- c("id", "days", "MAD")
ratings_MAD.wrist_long$MAD <- as.numeric(ratings_MAD.wrist_long$MAD)
ratings_MAD.wrist  <- reshape(ratings_MAD.wrist_long, idvar = "days", timevar = "id", direction = "wide")
ICC.MAD.wrist <- irr::icc(ratings_MAD.wrist[,-1], model = "twoway", type = "consistency")
ratings_MAD_25.wrist_long <- as.data.frame(cbind(axivity.estimates.wrist$id, axivity.estimates.wrist$days, axivity.estimates.wrist$MAD_25))
names(ratings_MAD_25.wrist_long) <- c("id", "days", "MAD")
ratings_MAD_25.wrist_long$MAD <- as.numeric(ratings_MAD_25.wrist_long$MAD)
ratings_MAD_25.wrist  <- reshape(ratings_MAD_25.wrist_long, idvar = "days", timevar = "id", direction = "wide")
ICC.MAD_25.wrist <- irr::icc(ratings_MAD_25.wrist[,-1], model = "twoway", type = "consistency")
ratings_MAD_75.wrist_long <- as.data.frame(cbind(axivity.estimates.wrist$id, axivity.estimates.wrist$days, axivity.estimates.wrist$MAD_75))
names(ratings_MAD_75.wrist_long) <- c("id", "days", "MAD")
ratings_MAD_75.wrist_long$MAD <- as.numeric(ratings_MAD_75.wrist_long$MAD)
ratings_MAD_75.wrist  <- reshape(ratings_MAD_75.wrist_long, idvar = "days", timevar = "id", direction = "wide")
ICC.MAD_75.wrist <- irr::icc(ratings_MAD_75.wrist[,-1], model = "twoway", type = "consistency")
ratings_MAD_25_dur.wrist_long <- as.data.frame(cbind(axivity.estimates.wrist$id, axivity.estimates.wrist$days, axivity.estimates.wrist$MAD_25_duration))
names(ratings_MAD_25_dur.wrist_long) <- c("id", "days", "MAD")
ratings_MAD_25_dur.wrist_long$MAD <- as.numeric(ratings_MAD_25_dur.wrist_long$MAD)
ratings_MAD_25_dur.wrist  <- reshape(ratings_MAD_25_dur.wrist_long, idvar = "days", timevar = "id", direction = "wide")
ICC.MAD_25_dur.wrist <- irr::icc(ratings_MAD_25_dur.wrist[,-1], model = "twoway", type = "consistency")
ratings_MAD_50_dur.wrist_long <- as.data.frame(cbind(axivity.estimates.wrist$id, axivity.estimates.wrist$days, axivity.estimates.wrist$MAD_50_duration))
names(ratings_MAD_50_dur.wrist_long) <- c("id", "days", "MAD")
ratings_MAD_50_dur.wrist_long$MAD <- as.numeric(ratings_MAD_50_dur.wrist_long$MAD)
ratings_MAD_50_dur.wrist  <- reshape(ratings_MAD_50_dur.wrist_long, idvar = "days", timevar = "id", direction = "wide")
ICC.MAD_50_dur.wrist <- irr::icc(ratings_MAD_50_dur.wrist[,-1], model = "twoway", type = "consistency")
ratings_MAD_75_dur.wrist_long <- as.data.frame(cbind(axivity.estimates.wrist$id, axivity.estimates.wrist$days, axivity.estimates.wrist$MAD_75_duration))
names(ratings_MAD_75_dur.wrist_long) <- c("id", "days", "MAD")
ratings_MAD_75_dur.wrist_long$MAD <- as.numeric(ratings_MAD_75_dur.wrist_long$MAD)
ratings_MAD_75_dur.wrist  <- reshape(ratings_MAD_75_dur.wrist_long, idvar = "days", timevar = "id", direction = "wide")
ICC.MAD_75_dur.wrist <- irr::icc(ratings_MAD_75_dur.wrist[,-1], model = "twoway", type = "consistency")

paste0("Wrist ENMO: ICC =" , ICC.ENMO.wrist$value, "[", ICC.ENMO.wrist$lbound, ";", ICC.ENMO.wrist$ubound, "]")
paste0("Wrist ENMO 25: ICC =" , ICC.ENMO_25.wrist$value, "[", ICC.ENMO_25.wrist$lbound, ";", ICC.ENMO_25.wrist$ubound, "]")
paste0("Wrist ENMO 75: ICC =" , ICC.ENMO_75.wrist$value, "[", ICC.ENMO_75.wrist$lbound, ";", ICC.ENMO_75.wrist$ubound, "]")
paste0("Wrist ENMO 25 dur: ICC =" , ICC.ENMO_25_dur.wrist$value, "[", ICC.ENMO_25_dur.wrist$lbound, ";", ICC.ENMO_25_dur.wrist$ubound, "]")
paste0("Wrist ENMO 50 dur: ICC =" , ICC.ENMO_50_dur.wrist$value, "[", ICC.ENMO_50_dur.wrist$lbound, ";", ICC.ENMO_50_dur.wrist$ubound, "]")
paste0("Wrist ENMO 75 dur: ICC =" , ICC.ENMO_75_dur.wrist$value, "[", ICC.ENMO_75_dur.wrist$lbound, ";", ICC.ENMO_75_dur.wrist$ubound, "]")

paste0("Wrist MAD: ICC =" , ICC.MAD.wrist$value, "[", ICC.MAD.wrist$lbound, ";", ICC.MAD.wrist$ubound, "]")
paste0("Wrist MAD 25: ICC =" , ICC.MAD_25.wrist$value, "[", ICC.MAD_25.wrist$lbound, ";", ICC.MAD_25.wrist$ubound, "]")
paste0("Wrist MAD 75: ICC =" , ICC.MAD_75.wrist$value, "[", ICC.MAD_75.wrist$lbound, ";", ICC.MAD_75.wrist$ubound, "]")

paste0("Wrist MAD 25 dur: ICC =" , ICC.MAD_25_dur.wrist$value, "[", ICC.MAD_25_dur.wrist$lbound, ";", ICC.MAD_25_dur.wrist$ubound, "]")
paste0("Wrist MAD 50 dur: ICC =" , ICC.MAD_50_dur.wrist$value, "[", ICC.MAD_50_dur.wrist$lbound, ";", ICC.MAD_50_dur.wrist$ubound, "]")
paste0("Wrist MAD 75 dur: ICC =" , ICC.MAD_75_dur.wrist$value, "[", ICC.MAD_75_dur.wrist$lbound, ";", ICC.MAD_75_dur.wrist$ubound, "]")

```


# My Little Moves app


## Step 6: Calculate number of days required to reach reliability

# Axivity

```{r Step 6 Axivity, echo=FALSE}
# Run the Spearman-Brown prophecy formula inputting single day ICCs for each outcome and defining
print("Results hip: To reach 0.7")
print("ENMO: ")
spearman.brown(singleICC = ICC.ENMO.hip$value, desiredR = 0.7)
print("ENMO_25: ")
spearman.brown(singleICC = ICC.ENMO_25.hip$value, desiredR = 0.7)
print("ENMO_75: ")
spearman.brown(singleICC = ICC.ENMO_75.hip$value, desiredR = 0.7)

print("ENMO_25_dur: ")
spearman.brown(singleICC = ICC.ENMO_25_dur.hip$value, desiredR = 0.7)
print("ENMO_50_dur: ")
spearman.brown(singleICC = ICC.ENMO_50_dur.hip$value, desiredR = 0.7)
print("ENMO_75_dur: ")
spearman.brown(singleICC = ICC.ENMO_75_dur.hip$value, desiredR = 0.7)

print("MAD: ")
spearman.brown(singleICC = ICC.MAD.hip$value, desiredR = 0.7)
print("MAD_25: ")
spearman.brown(singleICC = ICC.MAD_25.hip$value, desiredR = 0.7)
print("MAD_75: ")
spearman.brown(singleICC = ICC.MAD_75.hip$value, desiredR = 0.7)

print("MAD_25_dur: ")
spearman.brown(singleICC = ICC.MAD_25_dur.hip$value, desiredR = 0.7)
print("MAD_50_dur: ")
spearman.brown(singleICC = ICC.MAD_50_dur.hip$value, desiredR = 0.7)
print("MAD_75_dur: ")
spearman.brown(singleICC = ICC.MAD_75_dur.hip$value, desiredR = 0.7)


print("Results wrist: To reach 0.7")
print("ENMO: ")
spearman.brown(singleICC = ICC.ENMO.wrist$value, desiredR = 0.7)
print("ENMO_25: ")
spearman.brown(singleICC = ICC.ENMO_25.wrist$value, desiredR = 0.7)
print("ENMO_75: ")
spearman.brown(singleICC = ICC.ENMO_75.wrist$value, desiredR = 0.7)

print("ENMO_25_dur: ")
spearman.brown(singleICC = ICC.ENMO_25_dur.wrist$value, desiredR = 0.7)
print("ENMO_50_dur: ")
spearman.brown(singleICC = ICC.ENMO_50_dur.wrist$value, desiredR = 0.7)
print("ENMO_75_dur: ")
spearman.brown(singleICC = ICC.ENMO_75_dur.wrist$value, desiredR = 0.7)

print("MAD: ")
spearman.brown(singleICC = ICC.MAD.wrist$value, desiredR = 0.7)
print("MAD_25: ")
spearman.brown(singleICC = ICC.MAD_25.wrist$value, desiredR = 0.7)
print("MAD_75: ")
spearman.brown(singleICC = ICC.MAD_75.wrist$value, desiredR = 0.7)

print("MAD_25_dur: ")
spearman.brown(singleICC = ICC.MAD_25_dur.wrist$value, desiredR = 0.7)
print("MAD_50_dur: ")
spearman.brown(singleICC = ICC.MAD_50_dur.wrist$value, desiredR = 0.7)
print("MAD_75_dur: ")
spearman.brown(singleICC = ICC.MAD_75_dur.wrist$value, desiredR = 0.7)
```


```{r App feasibility}
valid_data_16h3d <- validday.app(data.app, minhours = 16, mindays = 3, savedir = filepath.app) 
length(unique(valid_data_16h3d$castorID))
length(unique(valid_data_16h3d$castorID)) / length(unique(data.app$castorID))

valid_data_16h4d <- validday.app(data.app, minhours = 16, mindays = 4, savedir = filepath.app) 
length(unique(valid_data_16h4d$castorID))
length(unique(valid_data_16h4d$castorID)) / length(unique(data.app$castorID))

```



# ```{r Heatmaps for required number of days MLM app}
# outcomes <- c("PA", "SB", "sleep", "ilr1", "ilr2")
# for(outcome in 1:outcomes){
#   if(outcomes[outcome] == "PA"){ temp <- ICC.PA
#   } else if(outcomes[outcome] == "SB"){ temp <- ICC.SB
#   } else if(outcomes[outcome] == "sleep"){ temp <- ICC.sleep
#   } else if(outcomes[outcome] == "ilr1"){ temp <- ICC.ilr1
#   } else { temp <- ICC.ilr2
#   }
#   heatmap_colors <- cut(temp$ICC, breaks = c(0, 0.70, 1), labels = c("red", "green"))
#   heatmap <- ggplot2::ggplot(temp, ggplot2::aes(x = hour, y = day, fill = ICC)) +
#   ggplot2::geom_tile(color = "white") +
#   #ggplot2::scale_fill_manual(values = c(red = "red", green = "green")) +
#   ggplot2::geom_text(ggplot2::aes(label = round(rel*100, 1)), color = "black", size = 2) +
#   ggplot2::labs(x = "Number of hours", y = "Number of days") +
#   ggplot2::theme_minimal() +
#   ggplot2::scale_x_continuous(breaks = round(unique(temp$hour))) +  
#   ggplot2::scale_y_continuous(breaks = round(unique(temp$day))) 
# print(heatmap)
# ggplot2::ggsave(filename = paste0(savedir, "MLMapp/reliability_", unique(temp.icc$outcome)[outcomes], ".jpeg"), plot = heatmap, width = 10, height = 8, units = "in", dpi = 300)
# }
# ```
